### ISSUE TITLE
Send SMS Permission Not Granted 

### ISSUE THREAD

**Issue by joelkanyi** [brandy-kay/Girl-Rescue#19]
Hello @brandy-kay 
When trying to send an emergency the app crashes.

Reason >>>>> You app used `<uses-permission android:name="android.permission.SEND_SMS" />`

But you did'nt request the user to grant you,

On First time launch, you need to request the permission and also before SMSs are sent, you need to check if the permission is granted just as you are checking if `Location` is enabled.

Thank you.

**Comment by brandy-kay** [comment]
Thanks @JoelKanyi  let me check on that
